python: "3.10"
random_seed: 42
confidence_min: 0.6
use_sample_data: false
data_path: "data/synthetic_fb_ads_undergarments.csv"
groq_model: "openai/gpt-oss-20b" 
groq_api_key: "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"
low_ctr_threshold: 0.01
